package iData.iItem
{
   public class EquipmentList
   {
      
      public static const list:Vector.<EquipmentData> = new <EquipmentData>[new WeaponData(Weapon.ONEHAND,WeaponType.SWORD,"sword","剑",new <RangeStat>[new RangeStat(Stat.attackMin,10,10),new RangeStat(Stat.attackMax,16,16),new RangeStat(Stat.balance,30,3),new RangeStat(Stat.crit,15,3)],WeaponCategory.MELEE,1),new WeaponData(Weapon.TWOHAND,WeaponType.AXE,"axe","斧",new <RangeStat>[new RangeStat(Stat.attackMin,5,5),new RangeStat(Stat.attackMax,24,24),new RangeStat(Stat.balance,15,3),new RangeStat(Stat.crit,15,3)],WeaponCategory.MELEE,2),new WeaponData(Weapon.TWOHAND,WeaponType.BOW,"bow","弓",new <RangeStat>[new RangeStat(Stat.attackMin,5,5),new RangeStat(Stat.attackMax,10,10),new RangeStat(Stat.balance,30,3),new RangeStat(Stat.crit,30,3)],WeaponCategory.RANGED,3),new WeaponData(Weapon.TWOHAND,WeaponType.CROSSBOW,"crossbow","弩",new <RangeStat>[new RangeStat(Stat.attackMin,10,10),new RangeStat(Stat.attackMax,16,16),new RangeStat(Stat.balance,15,3),new RangeStat(Stat.crit,30,3)],WeaponCategory.RANGED
      ,4),new WeaponData(Weapon.ONEHAND,WeaponType.SCEPTRE,"sceptre","权杖",new <RangeStat>[new RangeStat(Stat.attackMin,10,10),new RangeStat(Stat.attackMax,16,16),new RangeStat(Stat.balance,15,3),new RangeStat(Stat.crit,5,3)],WeaponCategory.MELEE,5),new WeaponData(Weapon.TWOHAND,WeaponType.STAFF,"staff","法杖",new <RangeStat>[new RangeStat(Stat.attackMin,10,10),new RangeStat(Stat.attackMax,16,16),new RangeStat(Stat.balance,30,3),new RangeStat(Stat.crit,15,3)],WeaponCategory.MELEE,6),new WeaponData(Weapon.OFFHAND,WeaponType.TOME,"tome","书",new <RangeStat>[new RangeStat(Stat.mp,10,10),new RangeStat(Stat.defence,1,4)],WeaponCategory.MELEE,7),new WeaponData(Weapon.OFFHAND,WeaponType.SHIELD,"shield","盾",new <RangeStat>[new RangeStat(Stat.defence,1,4),new RangeStat(Stat.protection,1,4)],WeaponCategory.MELEE,8),new WeaponData(Weapon.OFFHAND,WeaponType.DAGGER,"dagger","匕首",new <RangeStat>[new RangeStat(Stat.attackMin,5,5),new RangeStat(Stat.attackMax,8,8),new RangeStat(Stat.crit,5,3)],WeaponCategory.MELEE
      ,9),new EquipmentData(Equipment.BODY,EquipType.LIGHT,"suit","布衣",new <RangeStat>[new RangeStat(Stat.defence,1,4),new RangeStat(Stat.protection,1,2)],10),new EquipmentData(Equipment.BODY,EquipType.MEDIUM,"jerkin","皮衣",new <RangeStat>[new RangeStat(Stat.defence,1,2),new RangeStat(Stat.protection,1,4)],11),new EquipmentData(Equipment.BODY,EquipType.HEAVY,"breastplate","铠甲",new <RangeStat>[new RangeStat(Stat.defence,1,3),new RangeStat(Stat.protection,1,3)],12),new EquipmentData(Equipment.HEAD,EquipType.LIGHT,"fur hat","布帽",new <RangeStat>[new RangeStat(Stat.defence,1,4),new RangeStat(Stat.protection,1,2)],13),new EquipmentData(Equipment.HEAD,EquipType.MEDIUM,"felt hat","皮帽",new <RangeStat>[new RangeStat(Stat.defence,1,2),new RangeStat(Stat.protection,1,4)],14),new EquipmentData(Equipment.HEAD,EquipType.HEAVY,"helm","头盔",new <RangeStat>[new RangeStat(Stat.defence,1,3),new RangeStat(Stat.protection,1,3)],15),new EquipmentData(Equipment.FEET,EquipType.LIGHT,"Shoes","布鞋",new <RangeStat>[new RangeStat(Stat
      .defence,1,4),new RangeStat(Stat.protection,1,2)],16),new EquipmentData(Equipment.FEET,EquipType.MEDIUM,"Boots","皮鞋",new <RangeStat>[new RangeStat(Stat.defence,1,2),new RangeStat(Stat.protection,1,4)],17),new EquipmentData(Equipment.FEET,EquipType.HEAVY,"Greaves","铁靴",new <RangeStat>[new RangeStat(Stat.defence,1,3),new RangeStat(Stat.protection,1,3)],18),new EquipmentData(Equipment.NECKLACE,EquipType.ACCESORY,"necklace","项链",new Vector.<RangeStat>(0),19),new EquipmentData(Equipment.RING,EquipType.ACCESORY,"ring","戒指",new Vector.<RangeStat>(0),20)];
      
      public function EquipmentList()
      {
         super();
      }
   }
}

