package iData.iMap
{
   import iData.iMonster.MonsterData;
   import iData.iMonster.MonsterList;
   import iData.iPet.PetData;
   import iData.iPet.PetDataList;
   
   public class MapList
   {
      
      public static const list:Vector.<MapData> = new <MapData>[new MapData(85,314,"Town of Beginner","新手镇",0,new <MonsterData>[MonsterList.Young_Raccoon,MonsterList.Young_Gray_Raccoon,MonsterList.Young_Brown_Fox,MonsterList.White_Spiderling,MonsterList.White_Spider,MonsterList.Brown_Fox,MonsterList.Young_Red_Fox,MonsterList.Black_Town_Rat,MonsterList.Brown_Town_Rat],new <PetData>[PetDataList.att_fox,PetDataList.att_rat,PetDataList.def_fox,PetDataList.bal_fox]),new MapData(130,270,"Gairech Hill","格林山脉",0.4,new <MonsterData>[MonsterList.Raccoon,MonsterList.Old_Mimic,MonsterList.Red_Spiderling,MonsterList.Young_Gray_Fox,MonsterList.Giant_Spiderling,MonsterList.Red_Fox],new <PetData>[PetDataList.def_rat,PetDataList.att_rat,PetDataList.mag_rat,PetDataList.att_spider,PetDataList.def_spider,PetDataList.att_fox,PetDataList.def_fox,PetDataList.bal_fox]),new MapData(40,240,"Alby Peninsula","斯特莱恩",0.8,new <MonsterData>[MonsterList.White_Kiwi,MonsterList.Black_Kiwi,MonsterList.Green_Kiwi,MonsterList.Gold_Kiwi,MonsterList
      .Old_Sand_Mimic,MonsterList.Young_Goblin],new <PetData>[PetDataList.def_rat,PetDataList.att_rat,PetDataList.mag_rat,PetDataList.att_spider,PetDataList.def_spider,PetDataList.att_wolf,PetDataList.mag_wolf]),new MapData(115,170,"Forest of Souls","灵魂之森",1.2,new <MonsterData>[MonsterList.Dingo,MonsterList.Small_Ice_Worm,MonsterList.Stone_Mimic,MonsterList.Young_Poison_Goblin,MonsterList.Brown_tailed_Mongoose,MonsterList.White_Ant_Lion],new <PetData>[PetDataList.att_spider,PetDataList.def_spider,PetDataList.att_wolf,PetDataList.mag_wolf,PetDataList.def_bear,PetDataList.bal_bear]),new MapData(219,137,"Filia","费拉",1.6,new <MonsterData>[MonsterList.Cave_Rat,MonsterList.Goblin,MonsterList.Mimic,MonsterList.Masked_Goblin,MonsterList.Black_Aardvark,MonsterList.Black_Wolf,MonsterList.Brown_Dire_Wolf,MonsterList.Young_Brown_Warg],new <PetData>[PetDataList.att_wolf,PetDataList.mag_wolf,PetDataList.def_bear,PetDataList.bal_bear,PetDataList.att_bear]),new MapData(300,90,"The Frozen Shore","冰封角",2,new <MonsterData>[MonsterList
      .Bandersnatch,MonsterList.Blue_Snake,MonsterList.Kobold,MonsterList.Rat_Man,MonsterList.Red_Spider,MonsterList.White_Hair_Llama,MonsterList.Kobold_Bandit],new <PetData>[PetDataList.def_bear,PetDataList.bal_bear,PetDataList.att_bear,PetDataList.att_goblin,PetDataList.def_goblin,PetDataList.bal_goblin,PetDataList.mag_goblin]),new MapData(405,63,"Ghost Hill","幽魂谷",2.4,new <MonsterData>[MonsterList.Coyote,MonsterList.Zombie_Soldier,MonsterList.White_Bear,MonsterList.Maned_Aardvark,MonsterList.Stone_Hound,MonsterList.Goblin_Keeper,MonsterList.Bard_Skeleton,MonsterList.Bard_Skeleton],new <PetData>[PetDataList.att_goblin,PetDataList.def_goblin,PetDataList.bal_goblin,PetDataList.mag_goblin]),new MapData(440,156,"Misty Mountain","谜雾山",2.8,new <MonsterData>[MonsterList.Burgundy_Spider,MonsterList.Giant_Forest_Rat,MonsterList.Gold_Goblin,MonsterList.Gold_Kobold,MonsterList.Gray_Gremlin,MonsterList.Young_Lungfish,MonsterList.Jackal],new <PetData>[PetDataList.att_goblin,PetDataList.def_goblin,PetDataList
      .bal_goblin,PetDataList.mag_goblin]),new MapData(550,100,"The Bite","食人湾",3.2,new <MonsterData>[MonsterList.Stripeless_Hyena,MonsterList.Phantom_Silver_Tableware,MonsterList.Stone_Mask,MonsterList.Dragonfly,MonsterList.Imp,MonsterList.Ice_Sprite,MonsterList.Lightning_Sprite],new <PetData>[PetDataList.att_goblin,PetDataList.def_goblin,PetDataList.bal_goblin,PetDataList.mag_goblin,PetDataList.att_skeleton,PetDataList.def_skeleton,PetDataList.bal_skeleton,PetDataList.mag_skeleton]),new MapData(635,137,"The Gullet","加尔特",3.6,new <MonsterData>[MonsterList.Red_Lynx,MonsterList.Skeleton,MonsterList.Candle_Warrior,MonsterList.Guardian_Horse_of_Ruins,MonsterList.Gorgon,MonsterList.Stone_Horse,MonsterList.Topaz_Beetle,MonsterList.Brown_Bear],new <PetData>[PetDataList.att_skeleton,PetDataList.def_skeleton,PetDataList.bal_skeleton,PetDataList.mag_skeleton]),new MapData(680,189,"Casterly Rock","暴土城",4,new <MonsterData>[MonsterList.Red_Kobold,MonsterList.Stone_Zombie,MonsterList.Black_Buffalo,MonsterList
      .Shrieker,MonsterList.Long_Horn_Gnu,MonsterList.Wisp,MonsterList.Saturos,MonsterList.Skeleton_Ghost,MonsterList.Guardian_of_Ruins],new <PetData>[PetDataList.att_skeleton,PetDataList.def_skeleton,PetDataList.bal_skeleton,PetDataList.mag_skeleton,PetDataList.att_ghost,PetDataList.def_ghost,PetDataList.bal_ghost,PetDataList.mag_ghost]),new MapData(689,264,"Bone Cave","埋骨所",4.4,new <MonsterData>[MonsterList.Black_Succubus,MonsterList.Giant_Spider,MonsterList.Stone_Horse,MonsterList.Troll,MonsterList.Gnoll,MonsterList.Magic_Golem,MonsterList.Captain_Skeleton,MonsterList.Green_Snake,MonsterList.Lost_Sahuagin],new <PetData>[PetDataList.att_ghost,PetDataList.def_ghost,PetDataList.bal_ghost,PetDataList.mag_ghost]),new MapData(754,323,"Cape Warth","风怒角",4.8,new <MonsterData>[MonsterList.Hippo,MonsterList.Brown_Ixion,MonsterList.Incubus,MonsterList.Zombie,MonsterList.Bisque_Doll,MonsterList.Ogre,MonsterList.Esras,MonsterList.Ogre_Warrior,MonsterList.Giant_Ogre,MonsterList.Siren],new <PetData>[PetDataList
      .att_zombie,PetDataList.def_zombie,PetDataList.bal_zombie,PetDataList.mag_zombie]),new MapData(376,448,"Wyl","魔渊",5.2,new <MonsterData>[MonsterList.Lion,MonsterList.Balrog,MonsterList.Cyclops,MonsterList.Argus,MonsterList.Grendel,MonsterList.Cloaker,MonsterList.Wight,MonsterList.Ghost_Cloaker,MonsterList.Black_Warrior,MonsterList.Pink_Succubus,MonsterList.Spider_Warrior],new <PetData>[PetDataList.att_ruin,PetDataList.def_ruin,PetDataList.bal_ruin,PetDataList.mag_ruin]),new MapData(204,501,"Vaith","神墓",5.6,new <MonsterData>[MonsterList.Head_Hyena,MonsterList.Hellcat,MonsterList.Salamander,MonsterList.Banshee,MonsterList.Ruairi,MonsterList.Yeti,MonsterList.Mammoth,MonsterList.Giant_Sand_Worm,MonsterList.Ifrit],new <PetData>[PetDataList.att_ruin,PetDataList.def_ruin,PetDataList.bal_ruin,PetDataList.mag_ruin,PetDataList.def_unicorn,PetDataList.bal_unicorn]),new MapData(395,265,"???","???",6,new <MonsterData>[MonsterList.Prairie_Dragon,MonsterList.Giant_Lion,MonsterList.Arc_Lich,MonsterList.Desert_Dragon]
      ,new <PetData>[PetDataList.att_dragon,PetDataList.mag_dragon,PetDataList.def_unicorn,PetDataList.bal_unicorn])];
      
      public function MapList()
      {
         super();
      }
   }
}

