import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const root = join(__dirname, '..')
const spritesDir = join(root, 'public', 'sprites')

const dirs = readdirSync(spritesDir).filter((name) => {
  return statSync(join(spritesDir, name)).isDirectory()
})

const entries = []

for (const dir of dirs) {
  const fullDir = join(spritesDir, dir)
  const webpFiles = readdirSync(fullDir).filter((f) => f.endsWith('.webp'))
  const pngFiles = readdirSync(fullDir).filter((f) => f.endsWith('.png'))
  const ext = webpFiles.length > 0 ? 'webp' : 'png'
  const files = ext === 'webp' ? webpFiles : pngFiles
  const frames = files.length

  if (webpFiles.length > 0 && pngFiles.length > 0 && webpFiles.length !== pngFiles.length) {
    throw new Error(`${dir} has mismatched png/webp frame counts`)
  }

  const match = dir.match(/^DefineSprite_\d+_(.+)$/)
  const key = match ? match[1] : dir

  entries.push({ key, dir, frames, ext })
}

entries.sort((a, b) => a.key.localeCompare(b.key))

const lines = []
lines.push('// Auto-generated by scripts/generateSpriteRegistry.mjs')
lines.push('// DO NOT EDIT MANUALLY')
lines.push('')
lines.push('export interface SpriteRegistryEntry {')
lines.push('  dir: string')
lines.push('  frames: number')
lines.push("  ext?: 'png' | 'webp'")
lines.push('}')
lines.push('')
lines.push('export const spriteRegistry: Record<string, SpriteRegistryEntry> = {')

for (const { key, dir, frames, ext } of entries) {
  const extPart = ext === 'webp' ? ", ext: 'webp'" : ''
  if (frames === 1) {
    lines.push(`  '${key}': { dir: '${dir}', frames: 1${extPart} },`)
  } else {
    lines.push(`  '${key}': { dir: '${dir}', frames: ${frames}${extPart} }, // ${frames} frames`)
  }
}

lines.push('}')
lines.push('')
lines.push(`// Total: ${entries.length} sprites`)

const outPath = join(root, 'src', 'core', 'utils', 'spriteRegistry.ts')
writeFileSync(outPath, lines.join('\n'), 'utf-8')

console.log(`Generated ${entries.length} sprite entries → src/core/utils/spriteRegistry.ts`)

const multi = entries.filter((e) => e.frames > 1)
if (multi.length) {
  console.log(`  Multi-frame: ${multi.map((e) => `${e.key}(${e.frames}f)`).join(', ')}`)
}
